apiVersion: batch/v1
kind: Job
metadata:
  name: request
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: charllechen/mnist-k8s-client
        name: client-request
        env:
        - name: NUM_THREADS
          value: "100"
        - name: NUM_REQUESTS
          value: "1000"
        
