apiVersion: apps/v1
kind: Deployment
metadata:
    name: infer-mnist
    labels:
        app: api-mnist
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-mnist
    template:
        metadata:
            labels:
                app: api-mnist
        spec:
            containers:
                - name: infer
                  image: charllechen/mnist-k8s
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: infer-mnist-end
spec:
    type: LoadBalancer
    selector:
        app: api-mnist
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
