apiVersion: v1
kind: Service
metadata:
    name: infer-mnist-end
spec:
    type: LoadBalancer
    selector:
        app: api-mnist
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
